SELECT NAME,GRADE,MARKS FROM STUDENTS S,GRADES G 
WHERE MARKS BETWEEN MIN_MARK AND MAX_MARK AND GRADE > 7 
UNION
SELECT 'NULL' AS NAME,GRADE,MARKS FROM STUDENTS S,GRADES G 
WHERE MARKS BETWEEN MIN_MARK AND MAX_MARK AND GRADE<8
ORDER BY GRADE DESC,NAME,MARKS;